package Modelo;
// Generated 01/06/2018 00:14:58 by Hibernate Tools 4.3.1

import java.util.ArrayList;
import java.util.Date;
import java.util.List;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * Alunos generated by hbm2java
 */
@Entity
@Table(name = "alunos",
        catalog = "dadosk"
)
public class Alunos implements java.io.Serializable {

    private static final long serialVersionUID = 1L;

    private Integer idalunos;
    private Integer idclasse;
    private Date alunosData;
    private Integer alunosIdmembro;
    private Boolean licao1;
    private Boolean licao2;
    private Boolean licao3;
    private Boolean licao4;
    private Boolean licao5;
    private Boolean licao6;
    private Boolean licao7;
    private Boolean licao8;
    private Boolean licao9;
    private Boolean licao10;
    private Boolean licao11;
    private Boolean licao12;
    private Boolean licao13;
    private Boolean licao14;
    private Boolean licao15;
    private Boolean licao16;
    private Boolean licao17;
    private Boolean licao18;
    private Boolean licao19;
    private Boolean licao20;
    private Boolean licao21;
    private Boolean licao22;

    public Alunos() {
    }

    public Alunos(Integer idclasse, Date alunosData, Integer alunosIdmembro,
            Boolean licao1, Boolean licao2, Boolean licao3, Boolean licao4, Boolean licao5, Boolean licao6,
            Boolean licao7, Boolean licao8, Boolean licao9, Boolean licao10, Boolean licao11, Boolean licao12,
            Boolean licao13, Boolean licao14, Boolean licao15, Boolean licao16, Boolean licao17, Boolean licao18, Boolean licao19,
            Boolean licao20, Boolean licao21, Boolean licao22) {
        this.idclasse = idclasse;
        this.alunosData = alunosData;
        this.alunosIdmembro = alunosIdmembro;
        this.licao1 = licao1;
        this.licao1 = licao2;
        this.licao1 = licao3;
        this.licao1 = licao4;
        this.licao1 = licao5;
        this.licao1 = licao6;
        this.licao1 = licao7;
        this.licao1 = licao8;
        this.licao1 = licao9;
        this.licao1 = licao10;
        this.licao1 = licao11;
        this.licao1 = licao12;
        this.licao1 = licao13;
        this.licao1 = licao14;
        this.licao1 = licao15;
        this.licao1 = licao16;
        this.licao1 = licao17;
        this.licao1 = licao18;
        this.licao1 = licao19;
        this.licao1 = licao20;
        this.licao1 = licao21;
        this.licao1 = licao22;

    }

    @Id
    @GeneratedValue(strategy = IDENTITY)

    @Column(name = "idalunos", unique = true, nullable = false)
    public Integer getIdalunos() {
        return this.idalunos;
    }

    public void setIdalunos(Integer idalunos) {
        this.idalunos = idalunos;
    }

    @Column(name = "idclasse")
    public Integer getIdclasse() {
        return this.idclasse;
    }

    public void setIdclasse(Integer idclasse) {
        this.idclasse = idclasse;
    }

    @Temporal(TemporalType.DATE)
    @Column(name = "alunosData", length = 10)
    public Date getAlunosData() {
        return this.alunosData;
    }

    public void setAlunosData(Date alunosData) {
        this.alunosData = alunosData;
    }

    @Column(name = "alunosIDmembro")
    public Integer getAlunosIdmembro() {
        return this.alunosIdmembro;
    }

    public void setAlunosIdmembro(Integer alunosIdmembro) {
        this.alunosIdmembro = alunosIdmembro;
    }

    @Column(name = "licao1", length = 1)
    public Boolean getLicao1() {
        return licao1;
    }

    public void setLicao1(Boolean licao1) {
        this.licao1 = licao1;
    }

    @Column(name = "licao2", length = 1)
    public Boolean getLicao2() {
        return licao2;
    }

    public void setLicao2(Boolean licao2) {
        this.licao2 = licao2;
    }

    @Column(name = "licao3", length = 1)
    public Boolean getLicao3() {
        return licao3;
    }

    public void setLicao3(Boolean licao3) {
        this.licao3 = licao3;
    }

    @Column(name = "licao4", length = 1)
    public Boolean getLicao4() {
        return licao4;
    }

    public void setLicao4(Boolean licao4) {
        this.licao4 = licao4;
    }

    @Column(name = "licao5", length = 1)
    public Boolean getLicao5() {
        return licao5;
    }

    public void setLicao5(Boolean licao5) {
        this.licao5 = licao5;
    }

    @Column(name = "licao6", length = 1)
    public Boolean getLicao6() {
        return licao6;
    }

    public void setLicao6(Boolean licao6) {
        this.licao6 = licao6;
    }

    @Column(name = "licao7", length = 1)
    public Boolean getLicao7() {
        return licao7;
    }

    public void setLicao7(Boolean licao7) {
        this.licao7 = licao7;
    }

    @Column(name = "licao8", length = 1)
    public Boolean getLicao8() {
        return licao8;
    }

    public void setLicao8(Boolean licao8) {
        this.licao8 = licao8;
    }

    @Column(name = "licao9", length = 1)
    public Boolean getLicao9() {
        return licao9;
    }

    public void setLicao9(Boolean licao9) {
        this.licao9 = licao9;
    }

    @Column(name = "licao10", length = 1)
    public Boolean getLicao10() {
        return licao10;
    }

    public void setLicao10(Boolean licao10) {
        this.licao10 = licao10;
    }

    @Column(name = "licao11", length = 1)
    public Boolean getLicao11() {
        return licao11;
    }

    public void setLicao11(Boolean licao11) {
        this.licao11 = licao11;
    }

    @Column(name = "licao12", length = 1)
    public Boolean getLicao12() {
        return licao12;
    }

    public void setLicao12(Boolean licao12) {
        this.licao12 = licao12;
    }

    @Column(name = "licao13", length = 1)
    public Boolean getLicao13() {
        return licao13;
    }

    public void setLicao13(Boolean licao13) {
        this.licao13 = licao13;
    }

    @Column(name = "licao14", length = 1)
    public Boolean getLicao14() {
        return licao14;
    }

    public void setLicao14(Boolean licao14) {
        this.licao14 = licao14;
    }

    @Column(name = "licao15", length = 1)
    public Boolean getLicao15() {
        return licao15;
    }

    public void setLicao15(Boolean licao15) {
        this.licao15 = licao15;
    }

    @Column(name = "licao16", length = 1)
    public Boolean getLicao16() {
        return licao16;
    }

    public void setLicao16(Boolean licao16) {
        this.licao16 = licao16;
    }

    @Column(name = "licao17", length = 1)
    public Boolean getLicao17() {
        return licao17;
    }

    public void setLicao17(Boolean licao17) {
        this.licao17 = licao17;
    }

    @Column(name = "licao18", length = 1)
    public Boolean getLicao18() {
        return licao18;
    }

    public void setLicao18(Boolean licao18) {
        this.licao18 = licao18;
    }

    @Column(name = "licao19", length = 1)
    public Boolean getLicao19() {
        return licao19;
    }

    public void setLicao19(Boolean licao19) {
        this.licao19 = licao19;
    }

    @Column(name = "licao20", length = 1)
    public Boolean getLicao20() {
        return licao20;
    }

    public void setLicao20(Boolean licao20) {
        this.licao20 = licao20;
    }

    @Column(name = "licao21", length = 1)
    public Boolean getLicao21() {
        return licao21;
    }

    public void setLicao21(Boolean licao21) {
        this.licao21 = licao21;
    }

    @Column(name = "licao22", length = 1)
    public Boolean getLicao22() {
        return licao22;
    }

    public void setLicao22(Boolean licao22) {
        this.licao22 = licao22;
    }

}
