package Modelo;
// Generated 30/06/2018 15:56:14 by Hibernate Tools 4.3.1

import java.math.BigDecimal;
import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * Assinatura generated by hbm2java
 */
@Entity
@Table(name = "assinatura", catalog = "dadosk"
)
public class Assinatura implements java.io.Serializable {

    private Integer idassinatura;
    private Integer idperiodico;
    private Integer idmembro;
    private String observacao;
    private Date datacadastro;
    private String modalidade;
    private Integer qtdparcelas;
    private BigDecimal valortotal;

    public Assinatura() {
    }

    public Assinatura(Integer idassinatura, Integer idmembro, String observacao, Date datacadastro, String modalidade, Integer qtdparcelas, BigDecimal valortotal) {
        this.idassinatura = idassinatura;
        this.idmembro = idmembro;
        this.observacao = observacao;
        this.datacadastro = datacadastro;
        this.modalidade = modalidade;
        this.qtdparcelas = qtdparcelas;
        this.valortotal = valortotal;
    }

    @Id
    @GeneratedValue(strategy = IDENTITY)
    @Column(name = "idassinatura", unique = true, nullable = false)
    public Integer getIdassinatura() {
        return idassinatura;
    }

    public void setIdassinatura(Integer idassinatura) {
        this.idassinatura = idassinatura;
    }

    public Integer getIdperiodico() {
        return this.idperiodico;
    }

    public void setIdperiodico(Integer idperiodico) {
        this.idperiodico = idperiodico;
    }

    @Column(name = "idmembro")
    public Integer getIdmembro() {
        return this.idmembro;
    }

    public void setIdmembro(Integer idmembro) {
        this.idmembro = idmembro;
    }

    @Column(name = "observacao")
    public String getObservacao() {
        return this.observacao;
    }

    public void setObservacao(String observacao) {
        this.observacao = observacao;
    }

    @Temporal(TemporalType.DATE)
    @Column(name = "datacadastro", length = 10)
    public Date getDatadatacadastro() {
        return this.datacadastro;
    }

    public void setDatadatacadastro(Date datacadastro) {
        this.datacadastro = datacadastro;
    }

    @Column(name = "modalidade", length = 45)
    public String getModalidade() {
        return this.modalidade;
    }

    public void setModalidade(String modalidade) {
        this.modalidade = modalidade;
    }

    @Column(name = "qtdparcelas")
    public Integer getQtdparcelas() {
        return this.qtdparcelas;
    }

    public void setQtdparcelas(Integer qtdparcelas) {
        this.qtdparcelas = qtdparcelas;
    }

    @Column(name = "valortotal", precision = 7)
    public BigDecimal getValortotal() {
        return this.valortotal;
    }

    public void setValortotal(BigDecimal valortotal) {
        this.valortotal = valortotal;
    }

}
