package Modelo;
// Generated 11/05/2018 15:09:44 by Hibernate Tools 4.3.1


import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * Ata generated by hbm2java
 */
@Entity
@Table(name="ata"
    ,catalog="dadosk"
)
public class Ata  implements java.io.Serializable {


     private Integer idata;
     private Date ataData;
     private String ataTema;
     private String ataArquivo;

    public Ata() {
    }

    public Ata(Date ataData, String ataTema, String ataArquivo) {
       this.ataData = ataData;
       this.ataTema = ataTema;
       this.ataArquivo = ataArquivo;
    }
   
     @Id @GeneratedValue(strategy=IDENTITY)
    @Column(name = "idata", unique = true, nullable = false)
    public Integer getIdata() {
        return this.idata;
    }
    
    public void setIdata(Integer idata) {
        this.idata = idata;
    }

    @Temporal(TemporalType.DATE)
    @Column(name="ataData", length=10)
    public Date getAtaData() {
        return this.ataData;
    }
    
    public void setAtaData(Date ataData) {
        this.ataData = ataData;
    }

    
    @Column(name="ataTema", length=100)
    public String getAtaTema() {
        return this.ataTema;
    }
    
    public void setAtaTema(String ataTema) {
        this.ataTema = ataTema;
    }

    
    @Column(name="ataArquivo")
    public String getAtaArquivo() {
        return this.ataArquivo;
    }
    
    public void setAtaArquivo(String ataArquivo) {
        this.ataArquivo = ataArquivo;
    }




}


