package Modelo;
// Generated 26/06/2018 22:36:42 by Hibernate Tools 4.3.1


import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * Avisos generated by hbm2java
 */
@Entity
@Table(name="avisos"
    ,catalog="dadosk"
)
public class Avisos  implements java.io.Serializable {

    private static final long serialVersionUID = 1L;

     private Integer idAviso;
     private String arquivoAviso;
     private Date dataAviso;
     private String descriAviso;
     private Integer lido;
     private String titulo;
     private Date dataFinal;

    public Avisos() {
    }

    public Avisos(String arquivoAviso, Date dataAviso, String descriAviso, Integer lido, String titulo, Date dataFinal) {
       this.arquivoAviso = arquivoAviso;
       this.dataAviso = dataAviso;
       this.descriAviso = descriAviso;
       this.lido = lido;
       this.titulo = titulo;
       this.dataFinal = dataFinal;
    }
   
     @Id @GeneratedValue(strategy=IDENTITY)

    
    @Column(name="id_aviso", unique=true, nullable=false)
    public Integer getIdAviso() {
        return this.idAviso;
    }
    
    public void setIdAviso(Integer idAviso) {
        this.idAviso = idAviso;
    }

    
    @Column(name="arquivo_aviso", length=200)
    public String getArquivoAviso() {
        return this.arquivoAviso;
    }
    
    public void setArquivoAviso(String arquivoAviso) {
        this.arquivoAviso = arquivoAviso;
    }

    @Temporal(TemporalType.TIMESTAMP)
    @Column(name="data_aviso", length=19)
    public Date getDataAviso() {
        return this.dataAviso;
    }
    
    public void setDataAviso(Date dataAviso) {
        this.dataAviso = dataAviso;
    }

    
    @Column(name="descri_aviso")
    public String getDescriAviso() {
        return this.descriAviso;
    }
    
    public void setDescriAviso(String descriAviso) {
        this.descriAviso = descriAviso;
    }

    
    @Column(name="lido")
    public Integer getLido() {
        return this.lido;
    }
    
    public void setLido(Integer lido) {
        this.lido = lido;
    }

    
    @Column(name="titulo", length=200)
    public String getTitulo() {
        return this.titulo;
    }
    
    public void setTitulo(String titulo) {
        this.titulo = titulo;
    }

    @Temporal(TemporalType.TIMESTAMP)
    @Column(name="data_final", length=19)
    public Date getDataFinal() {
        return this.dataFinal;
    }
    
    public void setDataFinal(Date dataFinal) {
        this.dataFinal = dataFinal;
    }




}


