package Modelo;
// Generated 15/06/2018 12:08:11 by Hibernate Tools 4.3.1


import java.math.BigDecimal;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.Table;

/**
 * Caixa generated by hbm2java
 */
@Entity
@Table(name="caixa"
    ,catalog="dadosk"
)
public class Caixa  implements java.io.Serializable {


     private Integer idcaixa;
     private String descricao;
     private BigDecimal valordareceita;
     private BigDecimal valordadespesa;
     private BigDecimal saldo;

    public Caixa() {
    }

    public Caixa(String descricao, BigDecimal valordareceita, BigDecimal valordadespesa, BigDecimal saldo) {
       this.descricao = descricao;
       this.valordareceita = valordareceita;
       this.valordadespesa = valordadespesa;
       this.saldo = saldo;
    }
   
     @Id @GeneratedValue(strategy=IDENTITY)

    
    @Column(name="idcaixa", unique=true, nullable=false)
    public Integer getIdcaixa() {
        return this.idcaixa;
    }
    
    public void setIdcaixa(Integer idcaixa) {
        this.idcaixa = idcaixa;
    }

    
    @Column(name="descricao")
    public String getDescricao() {
        return this.descricao;
    }
    
    public void setDescricao(String descricao) {
        this.descricao = descricao;
    }

    
    @Column(name="valordareceita", precision=10)
    public BigDecimal getValordareceita() {
        return this.valordareceita;
    }
    
    public void setValordareceita(BigDecimal valordareceita) {
        this.valordareceita = valordareceita;
    }

    
    @Column(name="valordadespesa", precision=10)
    public BigDecimal getValordadespesa() {
        return this.valordadespesa;
    }
    
    public void setValordadespesa(BigDecimal valordadespesa) {
        this.valordadespesa = valordadespesa;
    }

    
    @Column(name="saldo", precision=10)
    public BigDecimal getSaldo() {
        return this.saldo;
    }
    
    public void setSaldo(BigDecimal saldo) {
        this.saldo = saldo;
    }




}


