package Modelo;
// Generated 04/06/2018 11:12:26 by Hibernate Tools 4.3.1


import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * Carta generated by hbm2java
 */
@Entity
@Table(name="carta"
    ,catalog="dadosk"
)
public class Carta  implements java.io.Serializable {

    private static final long serialVersionUID = 1L;

     private Integer idcarta;
     private String cartaNome;
     private String cartaIgrejaOrig;
     private Date cartaData;
     private String cartaArquivo;
     private String cartaTexto;

    public Carta() {
    }

    public Carta(String cartaNome, String cartaIgrejaOrig, Date cartaData, String cartaArquivo, String cartaTexto) {
       this.cartaNome = cartaNome;
       this.cartaIgrejaOrig = cartaIgrejaOrig;
       this.cartaData = cartaData;
       this.cartaArquivo = cartaArquivo;
       this.cartaTexto = cartaTexto;
    }
   
     @Id @GeneratedValue(strategy=IDENTITY)

    
    @Column(name="idcarta", unique=true, nullable=false)
    public Integer getIdcarta() {
        return this.idcarta;
    }
    
    public void setIdcarta(Integer idcarta) {
        this.idcarta = idcarta;
    }

    
    @Column(name="cartaNome", length=100)
    public String getCartaNome() {
        return this.cartaNome;
    }
    
    public void setCartaNome(String cartaNome) {
        this.cartaNome = cartaNome;
    }

    
    @Column(name="cartaIgrejaOrig")
    public String getCartaIgrejaOrig() {
        return this.cartaIgrejaOrig;
    }
    
    public void setCartaIgrejaOrig(String cartaIgrejaOrig) {
        this.cartaIgrejaOrig = cartaIgrejaOrig;
    }

    @Temporal(TemporalType.DATE)
    @Column(name="cartaData", length=10)
    public Date getCartaData() {
        return this.cartaData;
    }
    
    public void setCartaData(Date cartaData) {
        this.cartaData = cartaData;
    }

    
    @Column(name="cartaArquivo")
    public String getCartaArquivo() {
        return this.cartaArquivo;
    }
    
    public void setCartaArquivo(String cartaArquivo) {
        this.cartaArquivo = cartaArquivo;
    }

    
    @Column(name = "cartaTexto", length = 10000)
    public String getCartaTexto() {
        return this.cartaTexto;
    }
    
    public void setCartaTexto(String cartaTexto) {
        this.cartaTexto = cartaTexto;
    }




}


