package Modelo;
// Generated 16/05/2018 12:26:57 by Hibernate Tools 4.3.1

import java.text.ParseException;
import java.text.SimpleDateFormat;
import java.util.Date;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * Classes generated by hbm2java
 */
@Entity
@Table(name = "classes",
        catalog = "dadosk"
)
public class Classes implements java.io.Serializable {

    private static final long serialVersionUID = 1L;

    private int idclasses;
    private String classesNome;
    private String classesTipo;
    private Date classesData;
    private Integer classesQtdeMemb;
    private String classesLider1;
    private String classesLider2;
    private String classesLider3;
    private String classesLider4;
    private Date classesDtEncerra;
    private String classesObs;

    public Classes() {
    }

    
    public Classes(int idclasses) {
        this.idclasses = idclasses;
    }

    public Classes(int idclasses, String classesNome, String classesTipo, Date classesData, Integer classesQtdeMemb, String classesLider1, String classesLider2, String classesLider3, String classesLider4, Date classesDtEncerra, String classesObs) {
        this.idclasses = idclasses;
        this.classesNome = classesNome;
        this.classesTipo = classesTipo;
        this.classesData = classesData;
        this.classesQtdeMemb = classesQtdeMemb;
        this.classesLider1 = classesLider1;
        this.classesLider2 = classesLider2;
        this.classesLider3 = classesLider3;
        this.classesLider4 = classesLider4;
        this.classesDtEncerra = classesDtEncerra;
        this.classesObs = classesObs;
    }

    @Id
    @GeneratedValue(strategy = IDENTITY)
    @Column(name = "idclasses", unique = true, nullable = false)
    public int getIdclasses() {
        return this.idclasses;
    }

    public void setIdclasses(int idclasses) {
        this.idclasses = idclasses;
    }

    @Column(name = "classesNome", length = 100)
    public String getClassesNome() {
        return this.classesNome;
    }

    public void setClassesNome(String classesNome) {
        this.classesNome = classesNome.toUpperCase();
    }

    @Column(name = "classesTipo", length = 45)
    public String getClassesTipo() {
        return this.classesTipo;
    }

    public void setClassesTipo(String classesTipo) {
        this.classesTipo = classesTipo.toUpperCase();
    }

    @Temporal(TemporalType.DATE)
    @Column(name = "classesData", length = 10)
    public Date getClassesData() {
        return this.classesData;
    }

    public void setClassesData(Date classesData) {
        this.classesData = classesData;
    }

    @Column(name = "classesQtdeMemb")
    public Integer getClassesQtdeMemb() {
        return this.classesQtdeMemb;
    }

    public void setClassesQtdeMemb(Integer classesQtdeMemb) {
        this.classesQtdeMemb = classesQtdeMemb;
    }

    @Column(name = "classesLider1", length = 100)
    public String getClassesLider1() {
        return this.classesLider1;
    }

    public void setClassesLider1(String classesLider1) {
        this.classesLider1 = classesLider1;
    }

    @Column(name = "classesLider2", length = 100)
    public String getClassesLider2() {
        return this.classesLider2;
    }

    public void setClassesLider2(String classesLider2) {
        this.classesLider2 = classesLider2;
    }

    @Column(name = "classesLider3", length = 100)
    public String getClassesLider3() {
        return this.classesLider3;
    }

    public void setClassesLider3(String classesLider3) {
        this.classesLider3 = classesLider3;
    }

    @Column(name = "classesLider4", length = 100)
    public String getClassesLider4() {
        return this.classesLider4;
    }

    public void setClassesLider4(String classesLider4) {
        this.classesLider4 = classesLider4;
    }

    @Temporal(TemporalType.DATE)
    @Column(name = "classesDtEncerra", length = 10)
    public Date getClassesDtEncerra() {
        return this.classesDtEncerra;
    }

    public void setClassesDtEncerra(Date classesDtEncerra) {
        this.classesDtEncerra = classesDtEncerra;
    }

    @Column(name = "classesObs")
    public String getClassesObs() {
        return this.classesObs;
    }

    public void setClassesObs(String classesObs) {
        this.classesObs = classesObs;
    }

}
