package Modelo;
// Generated 31/07/2018 13:06:40 by Hibernate Tools 4.3.1


import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.Table;

/**
 * Classecontabil generated by hbm2java
 */
@Entity
@Table(name="classecontabil"
    ,catalog="dadosk"
)
public class Classecontabil  implements java.io.Serializable {


     private Integer id;
     private String tipo;

    public Classecontabil() {
    }

    public Classecontabil(String tipo) {
       this.tipo = tipo;
    }
   
     @Id @GeneratedValue(strategy=IDENTITY)

    
    @Column(name="id", unique=true, nullable=false)
    public Integer getId() {
        return this.id;
    }
    
    public void setId(Integer id) {
        this.id = id;
    }

    
    @Column(name="tipo")
    public String getTipo() {
        return this.tipo;
    }
    
    public void setTipo(String tipo) {
        this.tipo = tipo;
    }




}


