package Modelo;
// Generated 04/06/2018 11:12:26 by Hibernate Tools 4.3.1


import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * Criancas generated by hbm2java
 */
@Entity
@Table(name="criancas"
    ,catalog="dadosk"
)
public class Criancas  implements java.io.Serializable {


     private Integer idcriancas;
     private String criancasNome;
     private String criancasPai;
     private String criancasMae;
     private Date criancasData;
    private String criancasTelefone;
    private String criancasSexo;
    private Date criancasDataNasc;

    public Criancas() {
    }

    public Criancas(String criancasNome, String criancasPai, String criancasMae, Date criancasData, String criancasTelefone, String criancasSexo, Date criancasDataNasc) {
       this.criancasNome = criancasNome;
       this.criancasPai = criancasPai;
       this.criancasMae = criancasMae;
       this.criancasData = criancasData;
        this.criancasTelefone = criancasTelefone;
        this.criancasSexo = criancasSexo;
        this.criancasDataNasc = criancasDataNasc;
    }
   
    @Id
    @GeneratedValue(strategy = GenerationType.IDENTITY)
    @Column(name = "idcriancas", unique = true, nullable = false)
    public Integer getIdcriancas() {
        return this.idcriancas;
    }
    
    public void setIdcriancas(Integer idcriancas) {
        this.idcriancas = idcriancas;
    }

    
    @Column(name="criancasNome", length=100)
    public String getCriancasNome() {
        return this.criancasNome;
    }
    
    public void setCriancasNome(String criancasNome) {
        this.criancasNome = criancasNome;
    }

    
    @Column(name="criancasPai", length=100)
    public String getCriancasPai() {
        return this.criancasPai;
    }
    
    public void setCriancasPai(String criancasPai) {
        this.criancasPai = criancasPai;
    }

    
    @Column(name="criancasMae", length=100)
    public String getCriancasMae() {
        return this.criancasMae;
    }
    
    public void setCriancasMae(String criancasMae) {
        this.criancasMae = criancasMae;
    }

    @Temporal(TemporalType.DATE)
    @Column(name="criancasData", length=10)
    public Date getCriancasData() {
        return this.criancasData;
    }
    
    public void setCriancasData(Date criancasData) {
        this.criancasData = criancasData;
    }

    @Temporal(TemporalType.DATE)
    @Column(name = "criancasDataNasc", length = 10)
    public Date getCriancasDataNasc() {
        return criancasDataNasc;
    }

    public void setCriancasDataNasc(Date criancasDataNasc) {
        this.criancasDataNasc = criancasDataNasc;
    }


    
    @Column(name = "criancasTelefone")
    public String getCriancasTelefone() {
        return this.criancasTelefone;
    }
    
    public void setCriancasTelefone(String criancasTelefone) {
        this.criancasTelefone = criancasTelefone;
    }

    
    @Column(name = "criancasSexo", length = 10000)
    public String getCriancasSexo() {
        return this.criancasSexo;
    }
    
    public void setCriancasSexo(String criancasSexo) {
        this.criancasSexo = criancasSexo;
    }




}


