package Modelo;
// Generated 23/06/2018 17:01:59 by Hibernate Tools 4.3.1


import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * Diasdaescala generated by hbm2java
 */
@Entity
@Table(name="diasdaescala"
    ,catalog="dadosk"
)
public class Diasdaescala  implements java.io.Serializable {


     private Integer id;
     private Date data;
     private String hora;
     private String evento;
     private Integer idescalapai;

    public Diasdaescala() {
    }

    public Diasdaescala(Date data, String hora, String evento, Integer idescalapai) {
       this.data = data;
       this.hora = hora;
       this.evento = evento;
       this.idescalapai = idescalapai;
    }
   
     @Id @GeneratedValue(strategy=IDENTITY)

    
    @Column(name="id", unique=true, nullable=false)
    public Integer getId() {
        return this.id;
    }
    
    public void setId(Integer id) {
        this.id = id;
    }

    @Temporal(TemporalType.DATE)
    @Column(name="data", length=10)
    public Date getData() {
        return this.data;
    }
    
    public void setData(Date data) {
        this.data = data;
    }

    
    @Column(name="hora", length=45)
    public String getHora() {
        return this.hora;
    }
    
    public void setHora(String hora) {
        this.hora = hora;
    }

    
    @Column(name="evento")
    public String getEvento() {
        return this.evento;
    }
    
    public void setEvento(String evento) {
        this.evento = evento;
    }

    
    @Column(name="idescalapai")
    public Integer getIdescalapai() {
        return this.idescalapai;
    }
    
    public void setIdescalapai(Integer idescalapai) {
        this.idescalapai = idescalapai;
    }




}


