package Modelo;
// Generated 30/06/2018 15:56:14 by Hibernate Tools 4.3.1


import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.Table;

/**
 * Edicoes generated by hbm2java
 */
@Entity
@Table(name="edicoes"
    ,catalog="dadosk"
)
public class Edicoes  implements java.io.Serializable {


     private Integer idedicoes;
     private Integer idperiodico;
     private Integer idmembro;
     private Integer ed1;
     private Integer ed2;
     private Integer ed3;
     private Integer ed4;
     private Integer ed5;
     private Integer ed6;
     private Integer ed7;
     private Integer ed8;
     private Integer ed9;
     private Integer ed10;
     private Integer ed11;
     private Integer ed12;

    public Edicoes() {
    }

    public Edicoes(Integer idperiodico, Integer idmembro, Integer ed1, Integer ed2, Integer ed3, Integer ed4, Integer ed5, Integer ed6, Integer ed7, Integer ed8, Integer ed9, Integer ed10, Integer ed11, Integer ed12) {
       this.idperiodico = idperiodico;
       this.idmembro = idmembro;
       this.ed1 = ed1;
       this.ed2 = ed2;
       this.ed3 = ed3;
       this.ed4 = ed4;
       this.ed5 = ed5;
       this.ed6 = ed6;
       this.ed7 = ed7;
       this.ed8 = ed8;
       this.ed9 = ed9;
       this.ed10 = ed10;
       this.ed11 = ed11;
       this.ed12 = ed12;
    }
   
     @Id @GeneratedValue(strategy=IDENTITY)

    
    @Column(name="idedicoes", unique=true, nullable=false)
    public Integer getIdedicoes() {
        return this.idedicoes;
    }
    
    public void setIdedicoes(Integer idedicoes) {
        this.idedicoes = idedicoes;
    }

    
    @Column(name="idperiodico")
    public Integer getIdperiodico() {
        return this.idperiodico;
    }
    
    public void setIdperiodico(Integer idperiodico) {
        this.idperiodico = idperiodico;
    }

    
    @Column(name="idmembro")
    public Integer getIdmembro() {
        return this.idmembro;
    }
    
    public void setIdmembro(Integer idmembro) {
        this.idmembro = idmembro;
    }

    
    @Column(name="ed1")
    public Integer getEd1() {
        return this.ed1;
    }
    
    public void setEd1(Integer ed1) {
        this.ed1 = ed1;
    }

    
    @Column(name="ed2")
    public Integer getEd2() {
        return this.ed2;
    }
    
    public void setEd2(Integer ed2) {
        this.ed2 = ed2;
    }

    
    @Column(name="ed3")
    public Integer getEd3() {
        return this.ed3;
    }
    
    public void setEd3(Integer ed3) {
        this.ed3 = ed3;
    }

    
    @Column(name="ed4")
    public Integer getEd4() {
        return this.ed4;
    }
    
    public void setEd4(Integer ed4) {
        this.ed4 = ed4;
    }

    
    @Column(name="ed5")
    public Integer getEd5() {
        return this.ed5;
    }
    
    public void setEd5(Integer ed5) {
        this.ed5 = ed5;
    }

    
    @Column(name="ed6")
    public Integer getEd6() {
        return this.ed6;
    }
    
    public void setEd6(Integer ed6) {
        this.ed6 = ed6;
    }

    
    @Column(name="ed7")
    public Integer getEd7() {
        return this.ed7;
    }
    
    public void setEd7(Integer ed7) {
        this.ed7 = ed7;
    }

    
    @Column(name="ed8")
    public Integer getEd8() {
        return this.ed8;
    }
    
    public void setEd8(Integer ed8) {
        this.ed8 = ed8;
    }

    
    @Column(name="ed9")
    public Integer getEd9() {
        return this.ed9;
    }
    
    public void setEd9(Integer ed9) {
        this.ed9 = ed9;
    }

    
    @Column(name="ed10")
    public Integer getEd10() {
        return this.ed10;
    }
    
    public void setEd10(Integer ed10) {
        this.ed10 = ed10;
    }

    
    @Column(name="ed11")
    public Integer getEd11() {
        return this.ed11;
    }
    
    public void setEd11(Integer ed11) {
        this.ed11 = ed11;
    }

    
    @Column(name="ed12")
    public Integer getEd12() {
        return this.ed12;
    }
    
    public void setEd12(Integer ed12) {
        this.ed12 = ed12;
    }




}


