package Modelo;
// Generated 23/06/2018 17:01:59 by Hibernate Tools 4.3.1

import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * Escala generated by hbm2java
 */
@Entity
@Table(name = "escala",
        catalog = "dadosk"
)
public class Escala implements java.io.Serializable {

    private static final long serialVersionUID = 1L;

    private Integer idescala;
    private String escalaArquivo;
    private Integer escalaMes;
    private Integer escalaSemana;
    private Date escalaData;
    private Integer escalaPortao;
    private Integer escalaPorta;
    private Integer escalaGaleria;
    private Integer escalaDentro;
    private Integer escalaCorredor;
    private Integer escalaOficial1;
    private Integer escalaOficial2;
    private Integer escalaOficial3;
    private Integer escalaOficial4;
    private Integer secretario1;
    private Integer secretario2;
    private Boolean matriz;

    public Escala() {
    }

    public Escala(String escalaArquivo, Integer escalaMes, Integer escalaSemana, Date escalaData,
            Integer escalaPortao, Integer escalaPorta, Integer escalaGaleria, Integer escalaDentro,
            Integer escalaCorredor, Integer escalaOficial1, Integer escalaOficial2, Integer escalaOficial3,
            Integer escalaOficial4, Integer secretario1, Integer secretario2, Boolean matriz) {
        this.escalaArquivo = escalaArquivo;
        this.escalaMes = escalaMes;
        this.escalaSemana = escalaSemana;
        this.escalaData = escalaData;
        this.escalaPortao = escalaPortao;
        this.escalaPorta = escalaPorta;
        this.escalaGaleria = escalaGaleria;
        this.escalaDentro = escalaDentro;
        this.escalaCorredor = escalaCorredor;
        this.escalaOficial1 = escalaOficial1;
        this.escalaOficial2 = escalaOficial2;
        this.escalaOficial3 = escalaOficial3;
        this.escalaOficial4 = escalaOficial4;
        this.secretario1 = secretario1;
        this.secretario2 = secretario2;
        this.matriz = matriz;
    }

    @Id
    @GeneratedValue(strategy = IDENTITY)

    @Column(name = "idescala", unique = true, nullable = false)
    public Integer getIdescala() {
        return this.idescala;
    }

    public void setIdescala(Integer idescala) {
        this.idescala = idescala;
    }

    @Column(name = "escalaArquivo")
    public String getEscalaArquivo() {
        return this.escalaArquivo;
    }

    public void setEscalaArquivo(String escalaArquivo) {
        this.escalaArquivo = escalaArquivo;
    }

    @Column(name = "escalaMes")
    public Integer getEscalaMes() {
        return this.escalaMes;
    }

    public void setEscalaMes(Integer escalaMes) {
        this.escalaMes = escalaMes;
    }

    @Column(name = "escalaSemana")
    public Integer getEscalaSemana() {
        return this.escalaSemana;
    }

    public void setEscalaSemana(Integer escalaSemana) {
        this.escalaSemana = escalaSemana;
    }

    @Temporal(TemporalType.DATE)
    @Column(name = "escalaData", length = 10)
    public Date getEscalaData() {
        return this.escalaData;
    }

    public void setEscalaData(Date escalaData) {
        this.escalaData = escalaData;
    }

    @Column(name = "escalaPortao")
    public Integer getEscalaPortao() {
        return this.escalaPortao;
    }

    public void setEscalaPortao(Integer escalaPortao) {
        this.escalaPortao = escalaPortao;
    }

    @Column(name = "escalaPorta")
    public Integer getEscalaPorta() {
        return this.escalaPorta;
    }

    public void setEscalaPorta(Integer escalaPorta) {
        this.escalaPorta = escalaPorta;
    }

    @Column(name = "escalaGaleria")
    public Integer getEscalaGaleria() {
        return this.escalaGaleria;
    }

    public void setEscalaGaleria(Integer escalaGaleria) {
        this.escalaGaleria = escalaGaleria;
    }

    @Column(name = "escalaDentro")
    public Integer getEscalaDentro() {
        return this.escalaDentro;
    }

    public void setEscalaDentro(Integer escalaDentro) {
        this.escalaDentro = escalaDentro;
    }

    @Column(name = "escalaCorredor")
    public Integer getEscalaCorredor() {
        return this.escalaCorredor;
    }

    public void setEscalaCorredor(Integer escalaCorredor) {
        this.escalaCorredor = escalaCorredor;
    }

    @Column(name = "escalaOficial1")
    public Integer getEscalaOficial1() {
        return this.escalaOficial1;
    }

    public void setEscalaOficial1(Integer escalaOficial1) {
        this.escalaOficial1 = escalaOficial1;
    }

    @Column(name = "escalaOficial2")
    public Integer getEscalaOficial2() {
        return this.escalaOficial2;
    }

    public void setEscalaOficial2(Integer escalaOficial2) {
        this.escalaOficial2 = escalaOficial2;
    }

    @Column(name = "escalaOficial3")
    public Integer getEscalaOficial3() {
        return this.escalaOficial3;
    }

    public void setEscalaOficial3(Integer escalaOficial3) {
        this.escalaOficial3 = escalaOficial3;
    }

    @Column(name = "escalaOficial4")
    public Integer getEscalaOficial4() {
        return this.escalaOficial4;
    }

    public void setEscalaOficial4(Integer escalaOficial4) {
        this.escalaOficial4 = escalaOficial4;
    }

    @Column(name = "secretario1")
    public Integer getSecretario1() {
        return secretario1;
    }

    public void setSecretario1(Integer secretario1) {
        this.secretario1 = secretario1;
    }

    @Column(name = "secretario2")
    public Integer getSecretario2() {
        return secretario2;
    }

    public void setSecretario2(Integer secretario2) {
        this.secretario2 = secretario2;
    }

    @Column(name = "matriz")
    public Boolean getMatriz() {
        return matriz;
    }

    public void setMatriz(Boolean matriz) {
        this.matriz = matriz;
    }

}
