package Modelo;
// Generated 23/06/2018 17:01:59 by Hibernate Tools 4.3.1


import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * Escala generated by hbm2java
 */
@Entity
@Table(name="escala"
    ,catalog="dadosk"
)
public class Escala  implements java.io.Serializable {

    private static final long serialVersionUID = 1L;

     private Integer idescala;
     private String escalaArquivo;
     private Integer escalaMes;
     private Integer escalaSemana;
     private Date escalaData;
     private String escalaPortao;
     private String escalaPorta;
     private String escalaGaleria;
     private String escalaDentro;
     private String escalaCorredor;
     private String escalaOficial1;
     private String escalaOficial2;
     private String escalaOficial3;
    private String escalaOficial4;
    private String secretario1;
    private String secretario2;

    public Escala() {
    }

    public Escala(String escalaArquivo, Integer escalaMes, Integer escalaSemana, Date escalaData,
            String escalaPortao, String escalaPorta, String escalaGaleria, String escalaDentro,
            String escalaCorredor, String escalaOficial1, String escalaOficial2, String escalaOficial3,
            String escalaOficial4, String secretario1, String secretario2) {
       this.escalaArquivo = escalaArquivo;
       this.escalaMes = escalaMes;
       this.escalaSemana = escalaSemana;
       this.escalaData = escalaData;
       this.escalaPortao = escalaPortao;
       this.escalaPorta = escalaPorta;
       this.escalaGaleria = escalaGaleria;
       this.escalaDentro = escalaDentro;
       this.escalaCorredor = escalaCorredor;
       this.escalaOficial1 = escalaOficial1;
       this.escalaOficial2 = escalaOficial2;
       this.escalaOficial3 = escalaOficial3;
        this.escalaOficial4 = escalaOficial4;
        this.secretario1 = secretario1;
        this.secretario2 = secretario2;
    }
   
     @Id @GeneratedValue(strategy=IDENTITY)

    
    @Column(name="idescala", unique=true, nullable=false)
    public Integer getIdescala() {
        return this.idescala;
    }
    
    public void setIdescala(Integer idescala) {
        this.idescala = idescala;
    }

    
    @Column(name="escalaArquivo")
    public String getEscalaArquivo() {
        return this.escalaArquivo;
    }
    
    public void setEscalaArquivo(String escalaArquivo) {
        this.escalaArquivo = escalaArquivo;
    }

    
    @Column(name="escalaMes")
    public Integer getEscalaMes() {
        return this.escalaMes;
    }
    
    public void setEscalaMes(Integer escalaMes) {
        this.escalaMes = escalaMes;
    }

    
    @Column(name="escalaSemana")
    public Integer getEscalaSemana() {
        return this.escalaSemana;
    }
    
    public void setEscalaSemana(Integer escalaSemana) {
        this.escalaSemana = escalaSemana;
    }

    @Temporal(TemporalType.DATE)
    @Column(name="escalaData", length=10)
    public Date getEscalaData() {
        return this.escalaData;
    }
    
    public void setEscalaData(Date escalaData) {
        this.escalaData = escalaData;
    }

    
    @Column(name="escalaPortao")
    public String getEscalaPortao() {
        return this.escalaPortao;
    }
    
    public void setEscalaPortao(String escalaPortao) {
        this.escalaPortao = escalaPortao;
    }

    
    @Column(name="escalaPorta")
    public String getEscalaPorta() {
        return this.escalaPorta;
    }
    
    public void setEscalaPorta(String escalaPorta) {
        this.escalaPorta = escalaPorta;
    }

    
    @Column(name="escalaGaleria")
    public String getEscalaGaleria() {
        return this.escalaGaleria;
    }
    
    public void setEscalaGaleria(String escalaGaleria) {
        this.escalaGaleria = escalaGaleria;
    }

    
    @Column(name="escalaDentro")
    public String getEscalaDentro() {
        return this.escalaDentro;
    }
    
    public void setEscalaDentro(String escalaDentro) {
        this.escalaDentro = escalaDentro;
    }

    
    @Column(name="escalaCorredor")
    public String getEscalaCorredor() {
        return this.escalaCorredor;
    }
    
    public void setEscalaCorredor(String escalaCorredor) {
        this.escalaCorredor = escalaCorredor;
    }

    
    @Column(name="escalaOficial1")
    public String getEscalaOficial1() {
        return this.escalaOficial1;
    }
    
    public void setEscalaOficial1(String escalaOficial1) {
        this.escalaOficial1 = escalaOficial1;
    }

    
    @Column(name="escalaOficial2")
    public String getEscalaOficial2() {
        return this.escalaOficial2;
    }
    
    public void setEscalaOficial2(String escalaOficial2) {
        this.escalaOficial2 = escalaOficial2;
    }

    
    @Column(name="escalaOficial3")
    public String getEscalaOficial3() {
        return this.escalaOficial3;
    }
    
    public void setEscalaOficial3(String escalaOficial3) {
        this.escalaOficial3 = escalaOficial3;
    }

    
    @Column(name="escalaOficial4")
    public String getEscalaOficial4() {
        return this.escalaOficial4;
    }
    
    public void setEscalaOficial4(String escalaOficial4) {
        this.escalaOficial4 = escalaOficial4;
    }

    @Column(name = "secretario1")
    public String getSecretario1() {
        return secretario1;
    }

    public void setSecretario1(String secretario1) {
        this.secretario1 = secretario1;
    }

    @Column(name = "secretario2")
    public String getSecretario2() {
        return secretario2;
    }

    public void setSecretario2(String secretario2) {
        this.secretario2 = secretario2;
    }



}


