package Modelo;
// Generated 30/05/2018 16:05:06 by Hibernate Tools 4.3.1

import java.math.BigDecimal;
import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * Financeiro generated by hbm2java
 */
@Entity
@Table(name = "financeiro",
        catalog = "dadosk"
)
public class Financeiro implements java.io.Serializable {

    private Integer idfinanceiro;
    private Integer financeiroIdmembro;
    private BigDecimal financeiroValor;
    private String financeiroTipo;
    private Date financeiroData;

    public Financeiro() {
    }

    public Financeiro(Integer financeiroIdmembro, BigDecimal financeiroValor, String financeiroTipo, Date financeiroData) {
        this.financeiroIdmembro = financeiroIdmembro;
        this.financeiroValor = financeiroValor;
        this.financeiroTipo = financeiroTipo;
        this.financeiroData = financeiroData;
    }

    @Id
    @GeneratedValue(strategy = IDENTITY)

    @Column(name = "idfinanceiro", unique = true, nullable = false)
    public Integer getIdfinanceiro() {
        return this.idfinanceiro;
    }

    public void setIdfinanceiro(Integer idfinanceiro) {
        this.idfinanceiro = idfinanceiro;
    }

    @Column(name = "financeiroIDmembro")
    public Integer getFinanceiroIdmembro() {
        return this.financeiroIdmembro;
    }

    public void setFinanceiroIdmembro(Integer financeiroIdmembro) {
        this.financeiroIdmembro = financeiroIdmembro;
    }

    @Column(name = "financeiroVALOR", precision = 7)
    public BigDecimal getFinanceiroValor() {
        return this.financeiroValor;
    }

    public void setFinanceiroValor(BigDecimal financeiroValor) {
        this.financeiroValor = financeiroValor;
    }

    @Column(name = "financeiroTipo", length = 45)
    public String getFinanceiroTipo() {
        return this.financeiroTipo;
    }

    public void setFinanceiroTipo(String financeiroTipo) {
        this.financeiroTipo = financeiroTipo;
    }

    @Temporal(TemporalType.DATE)
    @Column(name = "financeiroData", length = 10)
    public Date getFinanceiroData() {
        return this.financeiroData;
    }

    public void setFinanceiroData(Date financeiroData) {
        this.financeiroData = financeiroData;
    }


}
