package Modelo;
// Generated 09/05/2018 15:58:39 by Hibernate Tools 4.3.1


import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.Table;

/**
 * Igrejas generated by hbm2java
 */
@Entity
@Table(name="igrejas"
    ,catalog="dadosk"
)
public class Igrejas  implements java.io.Serializable {

    private static final long serialVersionUID = 1L;

     private Integer idIgreja;
     private String nome;
     private String endereco;
     private String numero;
     private String complemento;
     private String bairro;
     private String cidade;
     private String estado;
     private String pais;
     private String cep;
     private String tipo;
     private String status;
     private String telefone;
     private String obs;
     private String dirigente;

    public Igrejas() {
    }

    public Igrejas(String nome, String endereco, String numero, String complemento, String bairro, String cidade, String estado, String pais, String cep, String tipo, String status, String telefone, String obs, String dirigente) {
       this.nome = nome;
       this.endereco = endereco;
       this.numero = numero;
       this.complemento = complemento;
       this.bairro = bairro;
       this.cidade = cidade;
       this.estado = estado;
       this.pais = pais;
       this.cep = cep;
       this.tipo = tipo;
       this.status = status;
       this.telefone = telefone;
       this.obs = obs;
       this.dirigente = dirigente;
    }
   
     @Id @GeneratedValue(strategy=IDENTITY)

    
    @Column(name="idIgreja", unique=true, nullable=false)
    public Integer getIdIgreja() {
        return this.idIgreja;
    }
    
    public void setIdIgreja(Integer idIgreja) {
        this.idIgreja = idIgreja;
    }

    
    @Column(name="Nome")
    public String getNome() {
        return this.nome;
    }
    
    public void setNome(String nome) {
        this.nome = nome;
    }

    
    @Column(name="Endereco")
    public String getEndereco() {
        return this.endereco;
    }
    
    public void setEndereco(String endereco) {
        this.endereco = endereco;
    }

    
    @Column(name="Numero")
    public String getNumero() {
        return this.numero;
    }
    
    public void setNumero(String numero) {
        this.numero = numero;
    }

    
    @Column(name="Complemento")
    public String getComplemento() {
        return this.complemento;
    }
    
    public void setComplemento(String complemento) {
        this.complemento = complemento;
    }

    
    @Column(name="Bairro")
    public String getBairro() {
        return this.bairro;
    }
    
    public void setBairro(String bairro) {
        this.bairro = bairro;
    }

    
    @Column(name="Cidade")
    public String getCidade() {
        return this.cidade;
    }
    
    public void setCidade(String cidade) {
        this.cidade = cidade;
    }

    
    @Column(name="Estado")
    public String getEstado() {
        return this.estado;
    }
    
    public void setEstado(String estado) {
        this.estado = estado;
    }

    
    @Column(name="Pais")
    public String getPais() {
        return this.pais;
    }
    
    public void setPais(String pais) {
        this.pais = pais;
    }

    
    @Column(name="Cep", length=15)
    public String getCep() {
        return this.cep;
    }
    
    public void setCep(String cep) {
        this.cep = cep;
    }

    
    @Column(name="Tipo", length=40)
    public String getTipo() {
        return this.tipo;
    }
    
    public void setTipo(String tipo) {
        this.tipo = tipo;
    }

    
    @Column(name="Status", length=40)
    public String getStatus() {
        return this.status;
    }
    
    public void setStatus(String status) {
        this.status = status;
    }

    
    @Column(name="Telefone", length=18)
    public String getTelefone() {
        return this.telefone;
    }
    
    public void setTelefone(String telefone) {
        this.telefone = telefone;
    }

    
    @Column(name="Obs")
    public String getObs() {
        return this.obs;
    }
    
    public void setObs(String obs) {
        this.obs = obs;
    }

    
    @Column(name="Dirigente")
    public String getDirigente() {
        return this.dirigente;
    }
    
    public void setDirigente(String dirigente) {
        this.dirigente = dirigente;
    }




}


