package Modelo;
// Generated 05/07/2018 17:58:24 by Hibernate Tools 4.3.1


import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * Missgeral generated by hbm2java
 */

public class Missgeral  implements java.io.Serializable {


     private Integer id;
     private Date datacadastro;
     private String nome;
     private String fone1;
     private String fone2;
     private String modalidade;
     private Long parcelaspg;
     private Integer valortotal;
     private Date parcela1;
     private Date parcela2;
     private Date parcela3;
     private Boolean ed1;
     private Boolean ed2;
     private Boolean ed3;
     private Boolean ed4;
     private Boolean ed5;
     private Boolean ed6;
     private Boolean ed7;
     private Boolean ed8;
     private Boolean ed9;
     private Boolean ed10;
     private Boolean ed11;
     private Boolean ed12;

    public Missgeral() {
    }

	
    public Missgeral(String nome) {
        this.nome = nome;
    }
    public Missgeral(Date datacadastro, String nome, String fone1, String fone2, String modalidade, Long parcelaspg, Integer valortotal, Date parcela1, Date parcela2, Date parcela3, Boolean ed1, Boolean ed2, Boolean ed3, Boolean ed4, Boolean ed5, Boolean ed6, Boolean ed7, Boolean ed8, Boolean ed9, Boolean ed10, Boolean ed11, Boolean ed12) {
       this.datacadastro = datacadastro;
       this.nome = nome;
       this.fone1 = fone1;
       this.fone2 = fone2;
       this.modalidade = modalidade;
       this.parcelaspg = parcelaspg;
       this.valortotal = valortotal;
       this.parcela1 = parcela1;
       this.parcela2 = parcela2;
       this.parcela3 = parcela3;
       this.ed1 = ed1;
       this.ed2 = ed2;
       this.ed3 = ed3;
       this.ed4 = ed4;
       this.ed5 = ed5;
       this.ed6 = ed6;
       this.ed7 = ed7;
       this.ed8 = ed8;
       this.ed9 = ed9;
       this.ed10 = ed10;
       this.ed11 = ed11;
       this.ed12 = ed12;
    }

    public Integer getId() {
        return id;
    }

    public void setId(Integer id) {
        this.id = id;
    }

    public Date getDatacadastro() {
        return datacadastro;
    }

    public void setDatacadastro(Date datacadastro) {
        this.datacadastro = datacadastro;
    }

    public String getNome() {
        return nome;
    }

    public void setNome(String nome) {
        this.nome = nome;
    }

    public String getFone1() {
        return fone1;
    }

    public void setFone1(String fone1) {
        this.fone1 = fone1;
    }

    public String getFone2() {
        return fone2;
    }

    public void setFone2(String fone2) {
        this.fone2 = fone2;
    }

    public String getModalidade() {
        return modalidade;
    }

    public void setModalidade(String modalidade) {
        this.modalidade = modalidade;
    }

    public Long getParcelaspg() {
        return parcelaspg;
    }

    public void setParcelaspg(Long parcelaspg) {
        this.parcelaspg = parcelaspg;
    }

    public Integer getValortotal() {
        return valortotal;
    }

    public void setValortotal(Integer valortotal) {
        this.valortotal = valortotal;
    }

    public Date getParcela1() {
        return parcela1;
    }

    public void setParcela1(Date parcela1) {
        this.parcela1 = parcela1;
    }

    public Date getParcela2() {
        return parcela2;
    }

    public void setParcela2(Date parcela2) {
        this.parcela2 = parcela2;
    }

    public Date getParcela3() {
        return parcela3;
    }

    public void setParcela3(Date parcela3) {
        this.parcela3 = parcela3;
    }

    public Boolean getEd1() {
        return ed1;
    }

    public void setEd1(Boolean ed1) {
        this.ed1 = ed1;
    }

    public Boolean getEd2() {
        return ed2;
    }

    public void setEd2(Boolean ed2) {
        this.ed2 = ed2;
    }

    public Boolean getEd3() {
        return ed3;
    }

    public void setEd3(Boolean ed3) {
        this.ed3 = ed3;
    }

    public Boolean getEd4() {
        return ed4;
    }

    public void setEd4(Boolean ed4) {
        this.ed4 = ed4;
    }

    public Boolean getEd5() {
        return ed5;
    }

    public void setEd5(Boolean ed5) {
        this.ed5 = ed5;
    }

    public Boolean getEd6() {
        return ed6;
    }

    public void setEd6(Boolean ed6) {
        this.ed6 = ed6;
    }

    public Boolean getEd7() {
        return ed7;
    }

    public void setEd7(Boolean ed7) {
        this.ed7 = ed7;
    }

    public Boolean getEd8() {
        return ed8;
    }

    public void setEd8(Boolean ed8) {
        this.ed8 = ed8;
    }

    public Boolean getEd9() {
        return ed9;
    }

    public void setEd9(Boolean ed9) {
        this.ed9 = ed9;
    }

    public Boolean getEd10() {
        return ed10;
    }

    public void setEd10(Boolean ed10) {
        this.ed10 = ed10;
    }

    public Boolean getEd11() {
        return ed11;
    }

    public void setEd11(Boolean ed11) {
        this.ed11 = ed11;
    }

    public Boolean getEd12() {
        return ed12;
    }

    public void setEd12(Boolean ed12) {
        this.ed12 = ed12;
    }
   
      


}


