package Modelo;
// Generated 30/06/2018 15:56:14 by Hibernate Tools 4.3.1


import java.math.BigDecimal;
import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * Parcelamentos generated by hbm2java
 */
@Entity
@Table(name="parcelamentos"
    ,catalog="dadosk"
)
public class Parcelamentos  implements java.io.Serializable {


     private Integer idparcelamentos;
     private Integer idmembro;
     private Integer idperiodico;
     private Integer numparcela;
     private BigDecimal valorparcela;
     private Date datapagamento;

    public Parcelamentos() {
    }

    public Parcelamentos(Integer idmembro, Integer idperiodico, Integer numparcela, BigDecimal valorparcela, Date datapagamento) {
       this.idmembro = idmembro;
       this.idperiodico = idperiodico;
       this.numparcela = numparcela;
       this.valorparcela = valorparcela;
       this.datapagamento = datapagamento;
    }
   
     @Id @GeneratedValue(strategy=IDENTITY)

    
    @Column(name="idparcelamentos", unique=true, nullable=false)
    public Integer getIdparcelamentos() {
        return this.idparcelamentos;
    }
    
    public void setIdparcelamentos(Integer idparcelamentos) {
        this.idparcelamentos = idparcelamentos;
    }

    
    @Column(name="idmembro")
    public Integer getIdmembro() {
        return this.idmembro;
    }
    
    public void setIdmembro(Integer idmembro) {
        this.idmembro = idmembro;
    }

    
    @Column(name="idperiodico")
    public Integer getIdperiodico() {
        return this.idperiodico;
    }
    
    public void setIdperiodico(Integer idperiodico) {
        this.idperiodico = idperiodico;
    }

    
    @Column(name="numparcela")
    public Integer getNumparcela() {
        return this.numparcela;
    }
    
    public void setNumparcela(Integer numparcela) {
        this.numparcela = numparcela;
    }

    
    @Column(name="valorparcela", precision=7)
    public BigDecimal getValorparcela() {
        return this.valorparcela;
    }
    
    public void setValorparcela(BigDecimal valorparcela) {
        this.valorparcela = valorparcela;
    }

    @Temporal(TemporalType.DATE)
    @Column(name="datapagamento", length=10)
    public Date getDatapagamento() {
        return this.datapagamento;
    }
    
    public void setDatapagamento(Date datapagamento) {
        this.datapagamento = datapagamento;
    }




}


