package Modelo;
// Generated 31/07/2018 13:06:40 by Hibernate Tools 4.3.1


import java.math.BigDecimal;
import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * Patrimonio generated by hbm2java
 */
@Entity
@Table(name="patrimonio"
    ,catalog="dadosk"
)
public class Patrimonio  implements java.io.Serializable {


     private Integer id;
     private String descricao;
     private Integer idcontabil;
     private String situacao;
     private Date dataaquisicao;
     private BigDecimal valor;
     private String obs;
     private String foto;

    public Patrimonio() {
    }

    public Patrimonio(String descricao, Integer idcontabil, String situacao, Date dataaquisicao, BigDecimal valor, String obs, String foto) {
       this.descricao = descricao;
       this.idcontabil = idcontabil;
       this.situacao = situacao;
       this.dataaquisicao = dataaquisicao;
       this.valor = valor;
       this.obs = obs;
       this.foto = foto;
    }
   
     @Id @GeneratedValue(strategy=IDENTITY)

    
    @Column(name="id", unique=true, nullable=false)
    public Integer getId() {
        return this.id;
    }
    
    public void setId(Integer id) {
        this.id = id;
    }

    
    @Column(name="descricao")
    public String getDescricao() {
        return this.descricao;
    }
    
    public void setDescricao(String descricao) {
        this.descricao = descricao;
    }

    
    @Column(name="idcontabil")
    public Integer getIdcontabil() {
        return this.idcontabil;
    }
    
    public void setIdcontabil(Integer idcontabil) {
        this.idcontabil = idcontabil;
    }

    
    @Column(name="situacao", length=45)
    public String getSituacao() {
        return this.situacao;
    }
    
    public void setSituacao(String situacao) {
        this.situacao = situacao;
    }

    @Temporal(TemporalType.DATE)
    @Column(name="dataaquisicao", length=10)
    public Date getDataaquisicao() {
        return this.dataaquisicao;
    }
    
    public void setDataaquisicao(Date dataaquisicao) {
        this.dataaquisicao = dataaquisicao;
    }

    
    @Column(name="valor", precision=10)
    public BigDecimal getValor() {
        return this.valor;
    }
    
    public void setValor(BigDecimal valor) {
        this.valor = valor;
    }

    
    @Column(name="obs")
    public String getObs() {
        return this.obs;
    }
    
    public void setObs(String obs) {
        this.obs = obs;
    }

    
    @Column(name="foto")
    public String getFoto() {
        return this.foto;
    }
    
    public void setFoto(String foto) {
        this.foto = foto;
    }




}


