package Modelo;
// Generated 30/06/2018 15:56:14 by Hibernate Tools 4.3.1

import java.math.BigDecimal;
import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * Periodico generated by hbm2java
 */
@Entity
@Table(name = "periodico", catalog = "dadosk"
)
public class Periodico implements java.io.Serializable {

    private Integer idperiodico;
    private String titulo;
    private BigDecimal valor;

    public Periodico() {
    }

    public Periodico(String titulo, Integer idperiodico, BigDecimal valor) {

        this.titulo = titulo;
        this.idperiodico = idperiodico;
        this.valor = valor;
    }

    @Id
    @GeneratedValue(strategy = IDENTITY)
    @Column(name = "idperiodico", unique = true, nullable = false)
    public Integer getIdperiodico() {
        return this.idperiodico;
    }

    public void setIdperiodico(Integer idperiodico) {
        this.idperiodico = idperiodico;
    }
    @Column(name = "titulo")
    public String getTitulo() {
        return this.titulo;
    }

    public void setTitulo(String titulo) {
        this.titulo = titulo;
    }


    @Column(name = "valor", precision = 7)
    public BigDecimal getValor() {
        return this.valor;
    }

    public void setValor(BigDecimal valor) {
        this.valor = valor;
    }

}
