package Modelo;
// Generated 07/05/2018 22:20:06 by Hibernate Tools 4.3.1


import java.io.Serializable;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.Table;

/**
 * Usuarios generated by hbm2java
 */
@Entity
@Table(name="usuarios"
    ,catalog="dadosk"
)
public class Usuarios implements Serializable {


     private Integer idUsuarios;
     private String nomeUsuarios;
     private String privilegiosUsuarios;
     private String senhaUsuarios;
     private Boolean financeiro;
     private Boolean secretaria;
     private Boolean missoes;
     private Boolean ebd;
    private Boolean administracao;
    private static final long serialVersionUID = 1L;

    public Usuarios() {
    }

    public Usuarios(String nomeUsuarios, String privilegiosUsuarios, String senhaUsuarios, Boolean financeiro, Boolean secretaria, Boolean missoes, Boolean ebd, Boolean administracao) {
       this.nomeUsuarios = nomeUsuarios;
       this.privilegiosUsuarios = privilegiosUsuarios;
       this.senhaUsuarios = senhaUsuarios;
       this.financeiro = financeiro;
       this.secretaria = secretaria;
       this.missoes = missoes;
       this.ebd = ebd;
       this.administracao = administracao;
    }
   
     @Id @GeneratedValue(strategy=IDENTITY)

    
    @Column(name="id_usuarios", unique=true, nullable=false)
    public Integer getIdUsuarios() {
        return this.idUsuarios;
    }
    
    public void setIdUsuarios(Integer idUsuarios) {
        this.idUsuarios = idUsuarios;
    }

    
    @Column(name="nome_usuarios", length=200)
    public String getNomeUsuarios() {
        return this.nomeUsuarios;
    }
    
    public void setNomeUsuarios(String nomeUsuarios) {
        this.nomeUsuarios = nomeUsuarios;
    }

    
    @Column(name="privilegios_usuarios", length=45)
    public String getPrivilegiosUsuarios() {
        return this.privilegiosUsuarios;
    }
    
    public void setPrivilegiosUsuarios(String privilegiosUsuarios) {
        this.privilegiosUsuarios = privilegiosUsuarios;
    }

    
    @Column(name="senha_usuarios", length=45)
    public String getSenhaUsuarios() {
        return this.senhaUsuarios;
    }
    
    public void setSenhaUsuarios(String senhaUsuarios) {
        this.senhaUsuarios = senhaUsuarios;
    }

    
    @Column(name="financeiro")
    public Boolean getFinanceiro() {
        return this.financeiro;
    }
    
    public void setFinanceiro(Boolean financeiro) {
        this.financeiro = financeiro;
    }

    
    @Column(name="secretaria")
    public Boolean getSecretaria() {
        return this.secretaria;
    }
    
    public void setSecretaria(Boolean secretaria) {
        this.secretaria = secretaria;
    }

    
    @Column(name="missoes")
    public Boolean getMissoes() {
        return this.missoes;
    }
    
    public void setMissoes(Boolean missoes) {
        this.missoes = missoes;
    }

    
    @Column(name="ebd")
    public Boolean getEbd() {
        return this.ebd;
    }
    
    public void setEbd(Boolean ebd) {
        this.ebd = ebd;
    }

    
    @Column(name="administracao")
    public Boolean getAdministracao() {
        return this.administracao;
    }
    
    public void setAdministracao(Boolean administracao) {
        this.administracao = administracao;
    }




}


