package Modelo;
// Generated 09/05/2018 22:55:01 by Hibernate Tools 4.3.1

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.Table;

/**
 * Veiculos generated by hbm2java
 */
@Entity
@Table(name = "veiculos",
        catalog = "dadosk"
)
public class Veiculos implements java.io.Serializable {

    private static final long serialVersionUID = 1L;
    private Integer idveiculos;
    private String veiculosPlaca;
    private String veiculosMarcaModelo;
    private String veiculosComustivel;
    private String veiculosAnoFab;
    private String veiculosCor;
    private String veiculosExecCrlv;
    private String veiculosAnoIpva;
    private String veiculosIpvapago;

    public Veiculos() {
    }

    public Veiculos(String veiculosPlaca, String veiculosMarcaModelo, String veiculosComustivel, String veiculosAnoFab, String veiculosCor, String veiculosExecCrlv, String veiculosAnoIpva, String veiculosIpvapago) {
        this.veiculosPlaca = veiculosPlaca;
        this.veiculosMarcaModelo = veiculosMarcaModelo;
        this.veiculosComustivel = veiculosComustivel;
        this.veiculosAnoFab = veiculosAnoFab;
        this.veiculosCor = veiculosCor;
        this.veiculosExecCrlv = veiculosExecCrlv;
        this.veiculosAnoIpva = veiculosAnoIpva;
        this.veiculosIpvapago = veiculosIpvapago;
    }

    @Id
    @GeneratedValue(strategy = IDENTITY)

    @Column(name = "idveiculos", unique = true, nullable = false)
    public Integer getIdveiculos() {
        return this.idveiculos;
    }

    public void setIdveiculos(Integer idveiculos) {
        this.idveiculos = idveiculos;
    }

    @Column(name = "veiculosPlaca", length = 45)
    public String getVeiculosPlaca() {
        return this.veiculosPlaca;
    }

    public void setVeiculosPlaca(String veiculosPlaca) {
        this.veiculosPlaca = veiculosPlaca;
    }

    @Column(name = "veiculosMarcaModelo", length = 100)
    public String getVeiculosMarcaModelo() {
        return this.veiculosMarcaModelo;
    }

    public void setVeiculosMarcaModelo(String veiculosMarcaModelo) {
        this.veiculosMarcaModelo = veiculosMarcaModelo;
    }

    @Column(name = "veiculosComustivel", length = 45)
    public String getVeiculosComustivel() {
        return this.veiculosComustivel;
    }

    public void setVeiculosComustivel(String veiculosComustivel) {
        this.veiculosComustivel = veiculosComustivel;
    }

    @Column(name = "veiculosAnoFab", length = 45)
    public String getVeiculosAnoFab() {
        return this.veiculosAnoFab;
    }

    public void setVeiculosAnoFab(String veiculosAnoFab) {
        this.veiculosAnoFab = veiculosAnoFab;
    }

    @Column(name = "veiculosCor", length = 45)
    public String getVeiculosCor() {
        return this.veiculosCor;
    }

    public void setVeiculosCor(String veiculosCor) {
        this.veiculosCor = veiculosCor;
    }

    @Column(name = "veiculosExecCRLV", length = 45)
    public String getVeiculosExecCrlv() {
        return this.veiculosExecCrlv;
    }

    public void setVeiculosExecCrlv(String veiculosExecCrlv) {
        this.veiculosExecCrlv = veiculosExecCrlv;
    }

    @Column(name = "veiculosAnoIPVA", length = 45)
    public String getVeiculosAnoIpva() {
        return this.veiculosAnoIpva;
    }

    public void setVeiculosAnoIpva(String veiculosAnoIpva) {
        this.veiculosAnoIpva = veiculosAnoIpva;
    }

    @Column(name = "veiculosIPVApago", length = 45)
    public String getVeiculosIpvapago() {
        return this.veiculosIpvapago;
    }

    public void setVeiculosIpvapago(String veiculosIpvapago) {
        this.veiculosIpvapago = veiculosIpvapago;
    }

}
